### ISSUE TITLE
Add a variable

### ISSUE THREAD

**Issue by Kcchouette** [areeb-beigh/RSS2IRC#4]
Hey

Is there a way to add [these two lines](https://github.com/areeb-beigh/RSS2IRC/blob/73b32d0692a4f70fa869eb46f22c688d77dcf2e4/rss2irc.py#L173,L174) - the admin mask, as a [variable like that](https://github.com/areeb-beigh/RSS2IRC/blob/73b32d0692a4f70fa869eb46f22c688d77dcf2e4/rss2irc.py#L28,L35)?

Thanks

**Comment by areebbeigh** [comment]
Hi, yes surely. I'll be updating this script ASAP. Currently I can't do it due to bad internet and stuff but I will get on it soon. I will keep this under consideration.

**Comment by areebbeigh** [comment]
As of the latest commit to RSS2IRC many features (including this one) and fixes have been added to the bot. Read the latest ReadMe for new configuration fields and commands.

https://github.com/areeb-beigh/RSS2IRC/commit/3ab56336d77fabd6b082f3c88d5bfdbae5255d17
